name: Build and deploy frontend

on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Opcional: si quieres ver info de Docker en logs
      - name: Show Docker info
        run: docker info

      - name: Build Docker image
        run: |
          docker build -t registro-frontend:latest .

      - name: Stop previous container
        run: |
          docker stop registro-frontend || true
          docker rm registro-frontend || true

      - name: Run new container
        run: |
          docker run -d \
            --name registro-frontend \
            -p 3000:3000 \
            --env-file /var/www/registro/.env.production \
            registro-frontend:latest